### ISSUE TITLE
Mistakingly used uncorrect input for bing cookies, now aih panic every time I invoke it

### ISSUE THREAD

**Issue by moisestohias** [Databingo/aih#1]
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/Databingo/EdgeGPT-Go/internal/CookieManager.(*Manager).findMinIndex(...)
	/Users/chengang/go/pkg/mod/github.com/!databingo/!edge!g!p!t-!go@v0.0.0-20230430071734-8b14b987728f/internal/CookieManager/manager.go:92
github.com/Databingo/EdgeGPT-Go/internal/CookieManager.(*Manager).GetBestCookie(0x1?)
	/Users/chengang/go/pkg/mod/github.com/!databingo/!edge!g!p!t-!go@v0.0.0-20230430071734-8b14b987728f/internal/CookieManager/manager.go:76 +0x131
github.com/Databingo/EdgeGPT-Go.NewGPT(0xc0000baf80)
	/Users/chengang/go/pkg/mod/github.com/!databingo/!edge!g!p!t-!go@v0.0.0-20230430071734-8b14b987728f/gpt.go:46 +0x3d
github.com/Databingo/EdgeGPT-Go.(*Storage).GetOrSet(0xc00011d4b8, {0xa359d1, 0x7})
	/Users/chengang/go/pkg/mod/github.com/!databingo/!edge!g!p!t-!go@v0.0.0-20230430071734-8b14b987728f/storage.go:31 +0xab
main.main()
	/usr/local/projects/aih/main.go:166 +0xbd8

**Comment by Databingo** [comment]
Hi thanks for replay.
You could remove the cookie file manually from the folder(suppose you put it in /usr/local/projects/aih) of Aih for now:
`rm -rf /usr/local/projects/aih/cookies`
Then restart Aih you could reset bing cookies via `bingkey`.
I would add cookie value checking to the code as soon as possible.
Thanks.

**Comment by Databingo** [comment]
Hi, I have added [bing cookie checking](https://github.com/Databingo/aih/commit/1b7718f227190d32abdf7f806bd67f53efeb2e4a).
Rebuild or download binary will fix the problem.
Thanks for your reports.

**Comment by moisestohias** [comment]
Thanks legend 😘
