### ISSUE TITLE
Mac Silicon (M1 Max) not working

### ISSUE THREAD

**Issue by dq-hustlecoding** [Databingo/aih#11]
just downloaded binary and executed `./aih`
it didn't go well.

anyone who experienced this?
<img width="746" alt="image" src="https://github.com/Databingo/aih/assets/91598674/6cce79d6-6ae9-4710-9f36-ec0e5cbde1ae">

**Comment by Databingo** [comment]
Did you closed your Chrome browser before run Aih at the first time?
Usually it needs letting Aih to restart you Chrome for reading user data at the first running.

**Comment by dq-hustlecoding** [comment]
Make sense,
Thanks!

**Comment by Databingo** [comment]
You are welcome :)
