### ISSUE TITLE
How to config cloude in slack app?

### ISSUE THREAD

**Issue by vjeson** [Databingo/aih#3]
I follow the step create a app and get the user oauth token. but can't get it work. Do i need to create a channel ,and add my app and claude app into the new channel ,use the new channel id?

For Cloude in Slack, [create an Slack App](https://api.slack.com/apps) by click Create New App, then click From scratch, then click Create App, find OAuth & Permissions->Scope->User Token Scope, add these promisions:
channels:history
channels:read
chat:write
files:write
groups:history
groups:read
im:history
im:read
im:write
mpim:history
mpim:read
team:read
users:read
then click Install to Workspace to find your User OAuth Token; You can obtain your channel_id by open the webside of chating with Claude in Slack via format of https://app.slack.com/client/xxxxx/yyyyy, then yyyyy is it.

**Comment by Databingo** [comment]
For my testing, no need creating a new channel.
Just add Claude to your Slack according to the [Claude's websit](https://www.anthropic.com/claude-in-slack), then create app & find you `User OAtuToken`, then find the Claude app' channel Id in the chating UI url:  `https://app.slack.com/client/xxxxx/yyyyy`, the yyyyy shoud be. So far if you could chat with Claude in Slack, you could chat in Aih.
Here is another tutorial of [configure of Claude in Slack](https://github-com.translate.goog/fffnower/chat_with_slack_claude?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=en&_x_tr_pto=wapp), you could follow it in details. 
<img src="https://github.com/Databingo/aih/assets/12667566/ef91b3f5-aa77-467d-9a17-e6b3a9510c75" width="400" >
PS: I also added a [wait response of Claude logic](https://github.com/Databingo/aih/commit/91a01e16e069a28ea444ce086d014dd0d2ba0e71) in code, hope it will prevent faults in usage.
Thank you for testing Aih!

**Comment by vjeson** [comment]
thanks 
it's my fault, I need to set proxy to use claude.

it's bettter to add a parameter to set proxy when new client, as below

`
func New(token,proxy string, options ...Option) *Client {
	client := &http.Client{}
	proxyUrl, err := url.Parse(proxy)
	if err != nil {
		return nil
	}
	transport := &http.Transport{Proxy: http.ProxyURL(proxyUrl)}
	client.Transport = transport

	s := &Client{
		token:      token,
		endpoint:   APIURL,
		httpclient: client,
		log:        log.New(os.Stderr, "slack-go/slack", log.LstdFlags|log.Lshortfile),
	}

	for _, opt := range options {
		opt(s)
	}

	return s
}

`

**Comment by Databingo** [comment]
Thank you, I guess you could use `.proxy` to set a proxy in Aih, and it will have global effect for Claude.
