### ISSUE TITLE
FEATURE-REQUEST:Save output to file

### ISSUE THREAD

**Issue by Haiz14** [Databingo/aih#5]
Something like  `./aih --chat "print helloworld in go" --output file.txy` to ask web chatGpt for answers

**Comment by Databingo** [comment]
Hi there, thanks for your attention to Aih!
Currently,  all the conversations are being saved in the history.txt file in the local directory. Is this the desired feature? Or would it be more appropriate to have an `export` command/parameter?

**Comment by Haiz14** [comment]
Export parameter would be nice. Thks a lott, you are awesome.

**Comment by Databingo** [comment]
Honestly, a specific command-line parameter for exporting a certain conversation is not an effective solution. For now, the history.txt file for recording all text works just fine. Thanks for your advice.
