### ISSUE TITLE
Claude Can not be used

### ISSUE THREAD

**Issue by QingShan-123** [Databingo/aih#6]
![image](https://github.com/Databingo/aih/assets/122095522/180c378e-6d93-4475-8bbf-8d0e83f6fd85)
first of all, we should add '@Claude ' before message， and then, we can not get response from claude.
![image](https://github.com/Databingo/aih/assets/122095522/1e238e70-66ca-41c4-9d6b-f15da87bd303)

**Comment by Databingo** [comment]
Sorry for replying late.
I found my claude for slack binding didn't work anymore since several weeks ago.
Maybe this API was detecting of the bot usage and do not response from the side of claude.
For now I haven't figure out the reason.
Sorry for this inconvenience.

**Comment by Databingo** [comment]
Now Claude2 work well, all prerequisite is a claude logged-in Chrome browser.
