### ISSUE TITLE
panic: runtime error

### ISSUE THREAD

**Issue by nunotexbsd** [Databingo/aih#8]
go 1.20

.bard> .key
✔ Set Google Bard Cookie
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x8a9950]

goroutine 1 [running]:
main.main()
        aih/main.go:516 +0x1d90
```

**Comment by Databingo** [comment]
Hi, thank you for the feedback.
I have just fixed the bug regarding the missing condition check before processing cleanup. Please try the v0.1.2.1 release or the latest code in the repository.
Thank you.
