### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Nickedude** [Databingo/aih#9]
Seems like a useful tool! :) Can you please add a license for it?

Best,
Niklas

**Comment by Databingo** [comment]
Hi! Thanks!

I really have no idea of license, do you have any suggestion?

**Comment by Nickedude** [comment]
I guess MIT license is pretty standard.
https://en.wikipedia.org/wiki/MIT_License

It's very permissive, and among other things it allows for modification, copying, usage in proprietary software, etc. 

Using a well-established, permissive, license increases the probability that people will use your tool! :)

**Comment by Databingo** [comment]
Hi Niklas,

According to your recommendation and the convenience of open-source community, I have decided to use the MIT license plus "You can choose not to include this MIT license into your copies".

Hope this is useful for users.
Regards
